### ISSUE TITLE
Integration Issue

### ISSUE THREAD

**Issue by Allwingit** [WoLpH/django-tags-input#20]
HI Team,
 I have tried to integrate tags-input with another project. I tried to use only tag input field in it. But i couldn't get proper results.

Could you give me your inputs on this ?
![26](https://user-images.githubusercontent.com/34136858/49210706-cdc27880-f3e3-11e8-92b2-e0555247dfe0.png)

Kindly find the below procedure I followed:

    1) created virtualenv

    2) Installed Django-tags-input (pip install -U django-tags-input)

    3) Created models with required fields.

    4) Added tags_input in Installed_App.

    5) Mapped that character field in TAG_INPUT_MAPPING
              TAGS_INPUT_MAPPINGS = {
                        'myapp.Questions': {'field': 'testtag', 'create_missing': True},
                       }

    6) added url path in url.py.
              url(r'^tags_input/', include('tags_input.urls', namespace='tags_input')),
    
     7)  inherit the TagsInputAdmin in admin.py

Is there anything i missed ?. If needed, I can share my sample code to verify tags-input.

**Comment by WoLpH** [comment]
It's hard to say what you've missed. To be certain that everything works I've created a new project and the workings myself and I don't appear to be getting any issues.

Looking at the screenshot I would think the `admin.py` might not be correct since it's not using the correct widget. But I'm not entirely sure, it's hard to say without the code
